### ISSUE TITLE
Todo's 

### ISSUE THREAD

**Issue by Mindgames** [INGRID360/stackedboost-shopify-assets#31]
- [x] Update name in the customizer to Simple Wordpress Post Feed
- [x] Update App name in assets to swpf
- [ ] Look over content sections

**Comment by Mindgames** [comment]
```
 eslint      ^6.5.1  →   ^6.6.0
 node-sass  ^4.12.0  →  ^4.13.0
```

**Comment by Mindgames** [comment]
- [ ] Add & config prettier to dev setup
